---
title: "Day 11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Input
```{r}
my_input <- read.csv("day_11_input.csv") %>% 
  separate(input, into = as.character(0:92), sep = "") %>% 
  select(-`0`)

my_input <- read.csv("day_11_test.csv") %>% 
  separate(input, into = as.character(0:10), sep = "") %>% 
  select(-`0`)
```

Part 1
```{r}
my_input

df <- my_input

for (k in 1:200){

  print(k)
  
new_df <- expand_grid(i = 1:99, j = 1:92) %>% 
  rowwise() %>% 
  mutate(seat_value = df[[i,j]],
         N = ifelse(i-1 != 0, df[[i-1, j]], NA),
         NE = ifelse(i-1 != 0 & j+1 != 93, df[[i-1, j + 1]], NA),
         E = ifelse(j+1 != 93, df[[i, j + 1]], NA),
         SE = ifelse(i+1 != 100 & j+1 != 93, df[[i+1, j+1]], NA),
         S = ifelse(i+1 != 100, df[[i+1, j]], NA),
         SW = ifelse(i+1 != 100 & j-1 != 0, df[[i+1, j-1]], NA),
         W = ifelse(j-1 != 0, df[[i, j-1]], NA),
         NW = ifelse(i-1 != 0 & j-1 != 0, df[[i-1, j-1]], NA)) %>% 
  pivot_longer(cols = c(-i, -j, -seat_value),
               names_to = "direction",
               values_to = "value") %>% 
  filter(!is.na(value)) %>% 
  group_by(i, j) %>% 
  mutate(total = n()) %>% 
  group_by(i, j, value) %>% 
  mutate(count = n(),
         prop = count / total,
         indicator = case_when(seat_value == "L" & value == "#" ~ 0,
                               seat_value == "L" ~ 1,
                               seat_value == "#" & value == "#" & count >= 4 ~ 1,
                               TRUE ~ 0)) %>% 
  ungroup() %>% 
  distinct(i, j, seat_value, indicator) %>% 
  group_by(i, j, seat_value) %>% 
  mutate(status = case_when(seat_value == "L" & min(indicator) == 1 ~ "change",
                            seat_value == "#" & max(indicator) == 1 ~ "change",
                            TRUE ~ "no change"),
         seat_value = case_when(status == "no change" ~ seat_value,
                                status == "change" & seat_value == "L" ~ "#",
                                status == "change" & seat_value == "#" ~ "L")) %>% 
  ungroup() %>% 
  distinct(i,j, seat_value) %>% 
  pivot_wider(names_from = j,
              values_from = seat_value) %>% 
  select(-i)

if(identical(new_df, df)){
  print("broken")
  break
}
df <- new_df
}

df %>% 
  pivot_longer(everything(),
               names_to = "name",
               values_to = "seat") %>% 
  group_by(seat) %>% 
  summarise(count = n())
```

Part 2
```{r}
my_input

df <- my_input

find_N <- function(i, j){
for (s in 1:15){
N = ifelse(i-s > 0, df[[i-s, j]], NA)
if(is.na(N) | N %in% c("L", "#")) {
  return(N)
  break
}
}
}

find_NE <- function(i, j){
for (s in 1:15){
NE = ifelse(i-s != 0 & j+s != 93, df[[i-s, j+s]], NA)
if(is.na(NE) | NE %in% c("L", "#")){
  return(NE)
  break
}
}
}

find_E <- function(i, j){
for (s in 1:15){
E = ifelse(j+s != 93, df[[i, j + s]], NA)
if(is.na(E) | E %in% c("L", "#")){
  return(E)
  break
}
}
}

find_SE <- function(i, j){
for (s in 1:15){
SE = ifelse(i+s != 100 & j+s != 93, df[[i+s, j+s]], NA)
if(is.na(SE) | SE %in% c("L", "#")){
  return(SE)
  break
}
}
}

find_S <- function(i, j){
for (s in 1:15){
S = ifelse(i+s != 100, df[[i+s, j]], NA)
if(is.na(S) | S %in% c("L", "#")){
  return(S)
  break
}
}
}

find_SW <- function(i, j){
for (s in 1:15){
SW = ifelse(i+s != 100 & j-s != 0, df[[i+s, j-s]], NA)
if(is.na(SW) | SW %in% c("L", "#")){
  return(SW)
  break
}
}
}

find_W <- function(i, j){
for (s in 1:15){
W = ifelse(j-s != 0, df[[i, j-s]], NA)
if(is.na(W) | W %in% c("L", "#")){
  return(W)
  break
}
}
}

find_NW <- function(i, j){
for (s in 1:15){
NW = ifelse(i-s != 0 & j-s != 0, df[[i-s, j-s]], NA)
NW
if(is.na(NW) | NW %in% c("L", "#")){
  return(NW)
  break
}
}
}

for (k in 1:1000){

  print(k)
  
new_df <- expand_grid(i = 1:99, j = 1:92) %>% 
  rowwise() %>% 
  mutate(seat_value = df[[i,j]],
         N = find_N(i, j),
         NE = find_NE(i, j),
         E = find_E(i, j),
         SE = find_SE(i, j),
         S = find_S(i, j),
         SW = find_SW(i, j),
         W = find_W(i, j),
         NW = find_NW(i, j)) %>% 
  pivot_longer(cols = c(-i, -j, -seat_value),
               names_to = "direction",
               values_to = "value") %>% 
  filter(!is.na(value)) %>% 
  group_by(i, j) %>% 
  mutate(total = n()) %>% 
  group_by(i, j, value) %>% 
  mutate(count = n(),
         prop = count / total,
         indicator = case_when(seat_value == "L" & value == "#" ~ 0,
                               seat_value == "L" ~ 1,
                               seat_value == "#" & value == "#" & count >= 5 ~ 1,
                               TRUE ~ 0)) %>% 
  ungroup() %>% 
  distinct(i, j, seat_value, indicator) %>% 
  group_by(i, j, seat_value) %>% 
  mutate(status = case_when(seat_value == "L" & min(indicator) == 1 ~ "change",
                            seat_value == "#" & max(indicator) == 1 ~ "change",
                            TRUE ~ "no change"),
         seat_value = case_when(status == "no change" ~ seat_value,
                                status == "change" & seat_value == "L" ~ "#",
                                status == "change" & seat_value == "#" ~ "L")) %>% 
  ungroup() %>% 
  distinct(i,j, seat_value) %>% 
  pivot_wider(names_from = j,
              values_from = seat_value) %>% 
  select(-i)

if(identical(new_df, df)){
  print("broken")
  break
}
df <- new_df
}

df %>% 
  pivot_longer(everything(),
               names_to = "name",
               values_to = "seat") %>% 
  group_by(seat) %>% 
  summarise(count = n())
```


